config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :slots
  root 'appointments#index'
  resources :appointments
  resources :doctors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :doctor
	belongs_to :slot
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	has_many :appointments
	has_many :slots
	belongs_to :user
end

app/models/slot.rb
class Slot < ApplicationRecord
	belongs_to :doctor
	has_one :appointment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:patient_name, :date_of_birth, :mobile, :email, :notes)
    end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :service)
    end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  before_action :set_slot, only: [:show, :edit, :update, :destroy]

  # GET /slots
  # GET /slots.json
  def index
    @slots = Slot.all
  end

  # GET /slots/1
  # GET /slots/1.json
  def show
  end

  # GET /slots/new
  def new
    @slot = Slot.new
  end

  # GET /slots/1/edit
  def edit
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = Slot.new(slot_params)

    respond_to do |format|
      if @slot.save
        format.html { redirect_to @slot, notice: 'Slot was successfully created.' }
        format.json { render :show, status: :created, location: @slot }
      else
        format.html { render :new }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html { redirect_to @slot, notice: 'Slot was successfully updated.' }
        format.json { render :show, status: :ok, location: @slot }
      else
        format.html { render :edit }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to slots_url, notice: 'Slot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slot
      @slot = Slot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slot_params
      params.require(:slot).permit(:starting_time, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/slots_helper.rb
module SlotsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :patient_name %>
    <%= form.text_field :patient_name, id: :appointment_patient_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.datetime_select :date_of_birth, id: :appointment_date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :mobile %>
    <%= form.text_field :mobile, id: :appointment_mobile %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :appointment_email %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :appointment_notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Patient name</th>
      <th>Date of birth</th>
      <th>Mobile</th>
      <th>Email</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.patient_name %></td>
        <td><%= appointment.date_of_birth %></td>
        <td><%= appointment.mobile %></td>
        <td><%= appointment.email %></td>
        <td><%= appointment.notes %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Patient name:</strong>
  <%= @appointment.patient_name %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @appointment.date_of_birth %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @appointment.mobile %>
</p>

<p>
  <strong>Email:</strong>
  <%= @appointment.email %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @appointment.notes %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/doctors/_form.html.erb
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :doctor_name %>
  </div>

  <div class="field">
    <%= form.label :service %>
    <%= form.text_field :service, id: :doctor_service %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Service</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.service %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Service:</strong>
  <%= @doctor.service %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panacea</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Panacea</a>

		  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
		    <ul class="navbar-nav pull-right">
		      <li class="nav-item">
		      	<% if user_signed_in? %>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete,  class: 'nav-link' %>
            <% else %>
              <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
            <% end %>
		      </li>
		    </ul>
		    <ul class="navbar-nav">

		    </ul>
		  </div>

    </nav>

    <%= yield %>
  </body>
</html>

app/views/slots/_form.html.erb
<%= form_with(model: slot, local: true) do |form| %>
  <% if slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
      <% slot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :starting_time %>
    <%= form.datetime_select :starting_time, id: :slot_starting_time %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status, id: :slot_status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/slots/edit.html.erb
<h1>Editing Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Show', @slot %> |
<%= link_to 'Back', slots_path %>

app/views/slots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Slots</h1>

<table>
  <thead>
    <tr>
      <th>Starting time</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slots.each do |slot| %>
      <tr>
        <td><%= slot.starting_time %></td>
        <td><%= slot.status %></td>
        <td><%= link_to 'Show', slot %></td>
        <td><%= link_to 'Edit', edit_slot_path(slot) %></td>
        <td><%= link_to 'Destroy', slot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slot', new_slot_path %>

app/views/slots/new.html.erb
<h1>New Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Back', slots_path %>

app/views/slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Starting time:</strong>
  <%= @slot.starting_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @slot.status %>
</p>

<%= link_to 'Edit', edit_slot_path(@slot) %> |
<%= link_to 'Back', slots_path %>